// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es/el-button')['default']
    ElForm: typeof import('element-plus/es/el-form')['default']
    ElFormItem: typeof import('element-plus/es/el-form-item')['default']
    ElFrom: typeof import('element-plus/es')['ElFrom']
    ElFromItem: typeof import('element-plus/es')['ElFromItem']
    ElInput: typeof import('element-plus/es/el-input')['default']
    ElTabPane: typeof import('element-plus/es/el-tab-pane')['default']
    ElTabs: typeof import('element-plus/es/el-tabs')['default']
    ElTree: typeof import('element-plus/es/el-tree')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}

export { }
